##### Python for High School

* [Table of Contents](PY4HS.ipynb)
* <a href="https://colab.research.google.com/github/4dsolutions/elite_school/blob/master/Pythonic_Andragogy_Notes.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
* [![nbviewer](https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg)](https://nbviewer.org/github/4dsolutions/elite_school/blob/master/Pythonic_Andragogy_Notes.ipynb)

# Pythonic Andragogy

We're looking at a big topic here, but only some notes underneath the umbrella.  The goal here is to look for organic connections among our topic areas.

### Self Publishing Basics

For example, given the planet as a starting point, we want to arrive at great circles by way of spinning, nested polyhedrons.  We'll be doing various charts and tables, along with the expected diagrams and animations.

A medium we expect to use is the web page, the contemporary surface for composition and display.  To that end, we wish to impart fluency with:

* HTML
* CSS
* in-browser code
* Markdown
* $\LaTeX$

where in-browser code is historically JavaScript (not Java).

In addition, we wish to explore:

* SQL
* Python
* 2D and 3D modeling
* Data Visualization


Within our curriculum and syllabus, we wish to integrate HTML + CSS in a seamless manner and in a way that reinforces other core topics, such as CHoPS, i.e. the Concontric Hierarchy of Polyhedron.

* [Digital Math](https://wikieducator.org/Digital_Math)
* [School of Tomorrow](https://github.com/4dsolutions/School_of_Tomorrow/blob/master/School_of_Tomorrow.ipynb)

### Concentric Hierarchy

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/51493803050" title="Concentric Hierarchy"><img src="https://live.staticflickr.com/65535/51493803050_c1923b3ff5_c.jpg" width="800" height="600" alt="Concentric Hierarchy"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
<br />
<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52868804828/in/datetaken/" title="Replit&#x27;s New Look"><img src="https://live.staticflickr.com/65535/52868804828_2dca24a657_c.jpg" width="800" height="504" alt="Replit&#x27;s New Look"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
<br />
<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52868221197/in/datetaken/" title="Improved Codepen"><img src="https://live.staticflickr.com/65535/52868221197_07be44960d_c.jpg" width="800" height="704" alt="Improved Codepen"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>


Here in the context of a Jupyter Notebook, we might want to focus on CSS as a format amenable to conversion.  CSS to Python dict.

### HTML + CSS

In [1]:
css = \
"""
body {
  color: black;
  font-family: Helvetica;
}
"""

rule_set = dict(body = {
                 "color": "black", 
                 "font-family": "Helvetica"})

Regular Expressions might be used in some parsing function, taking raw CSS to a corresponding dict format.  We're permitted to keep these associations looser than that, omitting said function.

Focusing on vocabulary, we want the selector, in this case `body` followed by the contents of the declaration block.  The two together comprise a ruleset.

In [2]:
import re

m = re.search(r"(\w+)\s+{", css)
m

<re.Match object; span=(1, 7), match='body {'>

In [3]:
m.group(0)

'body {'

In [4]:
body = m.group(1)
body

'body'

In [5]:
m = re.findall(r"[-\w]+:\s.\w+", css, re.M)
m

['color: black', 'font-family: Helvetica']

In [6]:
rule_set

{'body': {'color': 'black', 'font-family': 'Helvetica'}}

### JSON

JavaScript Object Notation (JSON) is very close to being parasable as a Python data structure, a dict in particular.  With only minor tweeks, we're able to go back and forth between our Python dict and corresponding JSON, for structured content transceiving purposes.

In [7]:
import json

In [8]:
json.dumps(rule_set)

'{"body": {"color": "black", "font-family": "Helvetica"}}'

### XML and HTML

XML traces to SGML, XHTML and to the whole idea of a Markup Language.  History enters the picture, and the evolution of standards.  When the World Wide Web (W3) got started, people say HTML as evolving from XML, and saw XML as the future of data structuring.  A lot of work was done in this area, around validation and schemas.  One could prove a document valid, and perform operations therewith.

The Ruby language, especially in the form of Ruby on Rails, was biased against XML and in favor of JSON.  We could say Ruby was a sign of the times, or that Ruby helped move us to a new time.

### Rules of the Road

Did you know an inch is 96 pixels long.  Pixels, along with picas and points, define a fixed length.  12 points make a pica.  An inch is 2.54 cm.  6 pc = 72 pt = 96 px.

Excerpt from *CSS in Depth* by Keith Grant:

<blockquote>
"Pixel" is a slightly misleading name—a CSS pixel does not strictly equate to a monitor’s pixel. This is notably the case on high-resolution (“retina”) displays. Although the CSS measurements can be scaled a bit, depending on the browser, the operating system, and the hardware, 96 px is usually in the ballpark of 1 physical inch onscreen, though this can vary on certain devices or with a user’s resolution settings.
</blockquote>

Tagging relates to nesting.

### Interactivity

What you want is some interactivity, including with buttons, using minimal JavaScript, if any.  Our CHoP is an ideal subject, as we selectively illuminate one or more shapes.  We could use checkboxes.

[Example using sliders](https://www.w3schools.com/css/css_colors_rgb.asp)

### Global Data

As mentioned at the outset, we have an interest in plotting global data on world maps and globes.  The polyhedrons, when spun around axes, take us to great circle networks.  We're happy to segue with latitude and logitude tables, to geo-locate major airports, weather stations, and so on.

Given the lat / long of any two airports, what is the straight line (geodesic) distance between them?  How might we graph the routes of any given airline, starting with a workable data structure?

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52632494223/in/album-72177720296706479/" title="Global Data"><img src="https://live.staticflickr.com/65535/52632494223_6ee936cd68.jpg" width="500" height="252" alt="Global Data"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

In [13]:
import sqlite3 as sql
import pandas as pd

conn = sql.connect("airports.db")
airports = pd.read_sql("select * from airports", conn)
conn.close()

In [15]:
airports.sample(10)

iata iso                                    name continent     type  \
4152  HNM  US                            Hana Airport        NA  airport   
3596  NIG  KI                         Nikunau Airport        OC  airport   
1657  DWA  MW                         Dwangwa Airport        AF  airport   
5215  SJU  PR  Luis Munoz Marin International Airport        NA  airport   
5769  BFV  TH                        Buri Ram Airport        AS  airport   
645   YZE  CA             Gore Bay Manitoulin Airport        NA  airport   
4344  GES  PH    General Santos International Airport        AS  airport   
4218  MMJ  JP                       Matsumoto Airport        AS  airport   
6545  TDT  ZA                      Tanda Tula Airport        AF  airport   
4251  HSG  JP                            Saga Airport        AS  airport   

            lat         lon    size  status  
4152  20.795834 -156.018890  medium       1  
3596  -1.333333  176.416670   small       1  
1657 -13.000000   34.133330  medium       1  
5215  18.437403  -66.004684   large       1  
5769  15.226944  103.255280  medium       1  
645   45.885277  -82.567780  medium       1  
4344   6.057778  125.095830  medium       1  
4218  36.233334  137.966660  medium       1  
6545 -24.533333   31.300000   small       1  
4251  33.153828  130.302780  medium       1

### Andragogy

When instructing adults, it behooves us to survey the state of the art, meaning online tools already available.  

Put yourself in the role of a student, newly encountering this material, even if it's material you've already learned.

For example, you may wish to steer towards, or away from, depending on your audience, the genre of cartoon animations (anime).  My bias is to steer towards.

Have you checked out [w3schools.com](https://www.w3schools.com/css/default.asp)?  Are you familiar with [regex101](https://regex101.com)?

### Array Based Computing

The Magic Square motivates introducing numpy n-dimensional arrays (ndarray type), as do several of our choice topics.

From [Learning Scientific Programming with Python](https://scipython.com/about/the-book/):


In [10]:
# Create an N x N magic square. N must be odd.
import numpy as np

N  = 11
magic_square = np.zeros((N,N), dtype=int)

n = 1
i, j = 0, N//2

while n <= N**2:
    magic_square[i, j] = n
    n += 1
    newi, newj = (i-1) % N, (j+1)% N
    if magic_square[newi, newj]:
        i += 1
    else:
        i, j = newi, newj

print(magic_square)

[[ 68  81  94 107 120   1  14  27  40  53  66]
 [ 80  93 106 119  11  13  26  39  52  65  67]
 [ 92 105 118  10  12  25  38  51  64  77  79]
 [104 117   9  22  24  37  50  63  76  78  91]
 [116   8  21  23  36  49  62  75  88  90 103]
 [  7  20  33  35  48  61  74  87  89 102 115]
 [ 19  32  34  47  60  73  86  99 101 114   6]
 [ 31  44  46  59  72  85  98 100 113   5  18]
 [ 43  45  58  71  84  97 110 112   4  17  30]
 [ 55  57  70  83  96 109 111   3  16  29  42]
 [ 56  69  82  95 108 121   2  15  28  41  54]]


What other languages are array-based?  BQN, APL, R...  Here's a place to take a detour.

### Tractor Math

Ever since [Automate the Boring Stuff with Python](https://automatetheboringstuff.com/) the link between this popular language and task automation has been a meme.  Controlling a process does not necessarily mean excluding humans.  Think coreography, with humans and their machines working in concert.

Tractor Math starts out as a kind of "Logo for Farmers" in that the initial shift is one of metaphors.  The focus because the field with its tractor.  

In practice, we need not invent whole new applications.  We might start in MIT Scratch, and then move to Codesters and Python.  We used that trajectory in *Coding with Kids* when I was an instructor in Portland, Oregon.

We look down from on high (drone view) at a field, whereon a tractor plows back and forth.  

Both the patterns of 

* reading (scanning rows of symbols) and of 
* television (raster pattern) 

have followed the field-plowing and field-planting patterns, of back and forth, or of starting over at the left or right, while moving along the rows.

Electron tunneling microscopy follows this pattern, as does weaving.

* [School of Tomorrow](https://github.com/4dsolutions/School_of_Tomorrow/blob/master/School_of_Tomorrow.ipynb)
* [The Farm](https://github.com/4dsolutions/elite_school/blob/master/thefarm.py)
* [Tractor Math 1](https://github.com/4dsolutions/elite_school/blob/master/tractor_1.py)
* [Tractor Math 2](https://github.com/4dsolutions/elite_school/blob/master/tractor_2.py)

