##### Python for High School

* [Table of Contents](PY4HS.ipynb)
* <a href="https://colab.research.google.com/github/4dsolutions/elite_school/blob/master/Pythonic_Andragogy.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
* [![nbviewer](https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg)](https://nbviewer.org/github/4dsolutions/elite_school/blob/master/Pythonic_Andragogy.ipynb)

*originally developed with assistance from Sunshine Elite Education, across several teaching opportunities.*

# Pythonic Andragogy

We're looking at a big topic here, but only some notes underneath the umbrella.  The goal here is to look for organic connections among our topic areas.

### Self Publishing Basics

For example, given the planet as a starting point, we want to arrive at great circles by way of spinning, nested polyhedrons.  We'll be doing various charts and tables, along with the expected diagrams and animations.

A medium we expect to use is the web page, the contemporary surface for composition and display.  To that end, we wish to impart fluency with:

* HTML
* CSS
* in-browser code

where in-browser code is historically JavaScript (not Java).

In addition, we wish to explore:

* SQL
* Python
* Markdown
* $\LaTeX$

We want to integrate HTML + CSS in a seamless manner, and in a way that reinforces topics covered elsewhere, such as CHoPS, the Concontric Hierarchy of Polyhedrons.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/51493803050" title="Concentric Hierarchy"><img src="https://live.staticflickr.com/65535/51493803050_c1923b3ff5_c.jpg" width="800" height="600" alt="Concentric Hierarchy"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
<br />
<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52868804828/in/datetaken/" title="Replit&#x27;s New Look"><img src="https://live.staticflickr.com/65535/52868804828_2dca24a657_c.jpg" width="800" height="504" alt="Replit&#x27;s New Look"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
<br />
<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52868221197/in/datetaken/" title="Improved Codepen"><img src="https://live.staticflickr.com/65535/52868221197_07be44960d_c.jpg" width="800" height="704" alt="Improved Codepen"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>


Here in the context of a Jupyter Notebook, we might want to focus on CSS as a format amenable to conversion.  CSS to Python dict.

In [1]:
css = \
"""
body {
  color: black;
  font-family: Helvetica;
}
"""

rule_set = dict(body = {
                 "color": "black", 
                 "font-family": "Helvetica"})

Regular Expressions might be used in some parsing function, taking raw CSS to a corresponding dict format.  We're permitted to keep these associations looser than that, omitting said function.

Focusing on vocabulary, we want the selector, in this case `body` followed by the contents of the declaration block.  The two together comprise a ruleset.

In [2]:
import re

m = re.search(r"(\w+)\s+{", css)
m

<re.Match object; span=(1, 7), match='body {'>

In [3]:
m.group(0)

'body {'

In [4]:
body = m.group(1)
body

'body'

In [5]:
m = re.findall(r"[-\w]+:\s.\w+", css, re.M)
m

['color: black', 'font-family: Helvetica']

In [6]:
rule_set

{'body': {'color': 'black', 'font-family': 'Helvetica'}}

JavaScript Object Notation (JSON) is very close to being parasable as a Python data structure, a dict in particular.  With only minor tweeks, we're able to go back and forth between our Python dict and corresponding JSON, for structured content transceiving purposes.

In [7]:
import json

In [8]:
json.dumps(rule_set)

'{"body": {"color": "black", "font-family": "Helvetica"}}'

### Rules of the Road

Did you know an inch is 96 pixels long.  Pixels, along with picas and points, define a fixed length.  12 points make a pica.  An inch is 2.54 cm.  6 pc = 72 pt = 96 px.

Excerpt from *CSS in Depth* by Keith Grant:

<blockquote>
"Pixel" is a slightly misleading name—a CSS pixel does not strictly equate to a monitor’s pixel. This is notably the case on high-resolution (“retina”) displays. Although the CSS measurements can be scaled a bit, depending on the browser, the operating system, and the hardware, 96 px is usually in the ballpark of 1 physical inch onscreen, though this can vary on certain devices or with a user’s resolution settings.
</blockquote>

Tagging relates to nesting.

### Interactivity

What you want is some interactivity, including with buttons, using minimal JavaScript, if any.  Our CHoP is an ideal subject, as we selectively illuminate one or more shapes.  We could use checkboxes.

[Example using sliders](https://www.w3schools.com/css/css_colors_rgb.asp)

### Global Data

As mentioned at the outset, we have an interest in plotting global data on world maps and globes.  The polyhedrons, when spun around axes, take us to great circle networks.  We're happy to segue with latitude and logitude tables, to geo-locate major airports, weather stations, and so on.

Given the lat / long of any two airports, what is the straight line (geodesic) distance between them?  How might we graph the routes of any given airline, starting with a workable data structure?

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52632494223/in/album-72177720296706479/" title="Global Data"><img src="https://live.staticflickr.com/65535/52632494223_6ee936cd68.jpg" width="500" height="252" alt="Global Data"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

### Andragogy

When instructing adults, it behooves us to survey the state of the art, meaning online tools already available.  

Put yourself in the role of a student, newly encountering this material, even if it's material you've already learned.

For example, you may wish to steer towards, or away from, depending on your audience, the genre of cartoon animations (anime).  My bias is to steer towards.

Have you checked out [w3schools.com](https://www.w3schools.com/css/default.asp)?  Are you familiar with [regex101](https://regex101.com)?

### Magic Square

The Magic Square motivates introducing numpy, as do several of our choice topics.

From [Learning Scientific Programming with Python](https://scipython.com/about/the-book/):


In [10]:
# Create an N x N magic square. N must be odd.
import numpy as np

N  = 11
magic_square = np.zeros((N,N), dtype=int)

n = 1
i, j = 0, N//2

while n <= N**2:
    magic_square[i, j] = n
    n += 1
    newi, newj = (i-1) % N, (j+1)% N
    if magic_square[newi, newj]:
        i += 1
    else:
        i, j = newi, newj

print(magic_square)

[[ 68  81  94 107 120   1  14  27  40  53  66]
 [ 80  93 106 119  11  13  26  39  52  65  67]
 [ 92 105 118  10  12  25  38  51  64  77  79]
 [104 117   9  22  24  37  50  63  76  78  91]
 [116   8  21  23  36  49  62  75  88  90 103]
 [  7  20  33  35  48  61  74  87  89 102 115]
 [ 19  32  34  47  60  73  86  99 101 114   6]
 [ 31  44  46  59  72  85  98 100 113   5  18]
 [ 43  45  58  71  84  97 110 112   4  17  30]
 [ 55  57  70  83  96 109 111   3  16  29  42]
 [ 56  69  82  95 108 121   2  15  28  41  54]]
